### ISSUE TITLE
MFHD only requests need to look at all copies to decide if something is Borrow Direct eligible

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#118]
When an item with multiple copies and multiple holdings is "Charged" the state of all other items needs to be considered. An item should only be eligible for Borrow Direct when all other copies are also "Charged" or restricted in some other way.

**Comment by kevinreiss** [comment]
@sdellis I think this is something we can take care of when re-factor the Borrow Direct Integration.

**Comment by kevinreiss** [comment]
@sdellis Could you look into what happens here with items that multiple holdings. I think we just want to confirm the appropriate behavior is invoked and borrow direct requests are not given as the default option when there are items at other PUL holding locations available.

**Comment by sdellis** [comment]
Yeah, this is not working correctly. See system_id: 4815239
Also, there is the case when an "online" resource is listed as "available", although there's no way for us to know the availability of an online resource. See system_id: 10015208

**Comment by kevinreiss** [comment]
For 4815239 we have two locally available copies, one on reserve and another at a non-circulating locoation. Borrow Direct will allow you to request this item because it is aware that those two locations are non-circulating. We should adjust the form to allow you to make a 'bd' request for items that might fall into this scenario.

**Comment by sdellis** [comment]
Oh, I did not realize the Engineering library copy was not available. If that's the case, then it _is_ working correctly in that scenario. I will need to find another example that will allow us to test this.

**Comment by kevinreiss** [comment]
It isn't entirely since the information displayed should reflect the temporary engineering location rather than the permanent stokes location. #137 should address this. The problem is the engineering reserve location is flagged as circulates=true. The ```has_loanable_copy?``` copy method is written to use that flag as the toggle as to whether or not an item with an available status is available. That isn't really reflective of the lending scenario for borrow direct since reserve locations usually are 2 or 24 hour loans.

**Comment by sdellis** [comment]
Ok, I have discovered a number of issues (documenting here just to remember to test all scenarios):

1. `requests/9003434?mfhd=9061233` has the following services ['bd','ill', 'recall'] but should not have any since there's a loanable copy available at Princeton. There should probably be an alert/notice on this page with a link to the page that lists all holdings (remove the mfhd param from the URL).
2. `requests/1389121` has an error when building the BorrowDirect pickup lists... investigating further. 
3. `requests/4815239` should allow BD lookup but does not. The question for circulation folks is whether or not ALL temp locations should be considered "non-circulating" for BD purposes. It would certainly help our patrons if an item at a temp/reserve location is eligible for BD, and I confirmed that BD allows this behavior, even for direct matches.

Finally, since [this record](https://pulsearch.princeton.edu/catalog/9003434) has a loanable copy, OL should not display the "Request" button on the "show" screen. We will work around this inconsistency and provide a way to loanable copies from the Request form, but just documenting here for @tampakis in case he wants to make a separate OL issue for future development.

**Comment by sdellis** [comment]
Number 2 in the list above has to do with one item being Missing and not adding pickup locations dropdown. Pickup locations is reused elsewhere for BD purposes. This is a bug, and is currently being fixed.

**Comment by sdellis** [comment]
Decision was made to generally ignore the mfhd for non-serials so that the BorrowDirect logic fires correctly, but to hide the items != mfhd param. If there is an available copy at Princeton, the user will be notified of the available copies. They will have the option to expand/show those items.
