### ISSUE TITLE
Remove "Trace Item" option from Mixed Holdings pages

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#164]
See: requests/2286894
Remove/disable checkboxes from Available Items on Mixed Holdings Pages. Any available multiple holdings page should not be "Traceable" as the button message says "Request". Request submission for Traceable items fails silently.

**Comment by kevinreiss** [comment]
See #162. Let's suppress trace options for now. Trace is odd case. My initial thought on this was that a user would come in to "trace" an item through a different path than the standard request workflows since they would never see a "request" button for a traceable item, so I had the idea we would have a special "trace" mode for the form that the form would be made aware of from the referring point the user wanted to "trace" the item form. My thought was that the stack mapping tools would be the place to reference the form in "trace" mode. Having a mode for trace would make it easy to change the verbiage of the form but still keep using all of the boilerplate bibliographic, holding, availability, and item data the standard form does. Since the circ staff wants to keep a low profile for this feature I think we can address this by the current recommendation.
