### ISSUE TITLE
Can't load request form

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#297]
See ID: 3149645. This item has mfhds with > 2000 items attached. Look into paging or some other optimization of the underlying oracle query in voyager_helpers.

**Comment by kevinreiss** [comment]
When https://github.com/pulibrary/marc_liberation/pull/305 this page will load in less 10 seconds compared to over two minutes. Now that the mfhd query is preformant we should consider re-factoring the form to allow for a lighter experience where only load twenty items or so at a time instead of dumping out 2,200 records. We might allow them to autocomplete volume and year information on item records with enumeration to wade through holdings with many items.

**Comment by kevinreiss** [comment]
Form loads in a reasonable amount of time after a switch to bibdata but on form submit an HTTP 413 error comes back due to the extreme number of form params.

**Comment by sdellis** [comment]
By the time a user gets to the Request page, they already know exactly what they want either 1) because they have a citation or 2) they have browsed the Table of Contents listings on the OL show page.  

Instead of offering users a monolithic "Request" button for a journal holding, I think it would be better to allow them to select the holding items they want from the OL page before clicking "Request" which would allow us to build a leaner form for the specific items. This could then use the bibdata Items service. Example: https://bibdata.princeton.edu/items/7484166

The alternative would be to refactor the entire submission method to be an ajax request that only POSTs the items that are selected. This would speed up the submission, but it would be a considerable effort and does nothing to address the obvious problem of the enormous form and all the usability and performance issues that come with it.

This is curious: for the example ID (3149645), I see that the OL sidebar displays the copies as checked out when they are not checked out on the Request form. I'm not sure why.

Having more than one example would also help determine what our options are for making this more usable.
