### ISSUE TITLE
Improve sorting on enumerated SCSB Items

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#358]
See what we can do on records like https://catalog.princeton.edu/catalog/SCSB-5936783. SCSB does not supply enumerated serials with a sequence integer like Voyager. String sorting may be iffy given the variability of how enumeration has been supplied.

**Comment by kevinreiss** [comment]
I think we can close this one with the new autocomplete search added last week. @axamei correct?

**Comment by axamei** [comment]
@kevinreiss The data table filtering is only applied to tables with more than 5 rows. It is not applied to the whole page. It is applied to each location's item table. See https://catalog.princeton.edu/requests/857469. 

For this record, can we put all the items under the same location, ReCAP, instead of listing each item in its own table in the request page? It also does not look great when separated individually on the item record page. 

<img width="1207" alt="Screen Shot 2020-06-09 at 8 38 03 AM" src="https://user-images.githubusercontent.com/8161144/84148417-f7268080-aa2c-11ea-9a97-5017066f649d.png">
<img width="893" alt="Screen Shot 2020-06-09 at 8 37 44 AM" src="https://user-images.githubusercontent.com/8161144/84148418-f7bf1700-aa2c-11ea-9bdf-4381ac4dca7f.png">

**Comment by kevinreiss** [comment]
Consider collapsing duplicate holdings and file all items under a single holding.

**Comment by carolyncole** [comment]
Since we have just one MFHD I think this can be closed.
