### ISSUE TITLE
Show other available items on request form

### ISSUE THREAD

**Issue by escowles** [pulibrary/requests#374]
When a user is requesting an item from ReCAP, show any available items as alternatives.  Find matching items by identifier (OCLC number? other identifiers?).

**Comment by sdellis** [comment]
It does this for items on reserve that can't be loaned. Can you share the use case for this proposed feature @escowles ?

**Comment by kevinreiss** [comment]
This would run for any item regardless of status and render a block containing information about copies attached to other bibliographic records since the current form business logic is scoped to only the holdings and items attached to the bib record.

**Comment by sdellis** [comment]
What I mean by "use case" is "Why is this change being proposed?" 

Is it because we assume that if a user is aware that an item is on the shelf, they will not request it from ReCAP? According to the usability study, lots of users simply request from home, wanting to pick up their books in one spot rather than walk all over the library (or libraries) tracking down books on the shelf. Or is this an attempt to solve the SCSB problem of people requesting items stored at ReCAP, when we would prefer them to get it from the shelf? 

Is the proposal to display the "Copies in Library" block of the non-SCSB "Other Version" in the column below for the Request app, along with the Online Version information ( [see record](https://catalog.princeton.edu/catalog/6925358) )? 

![screen shot 2018-08-13 at 1 59 58 pm](https://user-images.githubusercontent.com/609368/44057814-3fd47fd2-9f1a-11e8-9fcc-4c29c6b843c2.png)

In which case you would see this information in the Requests app?

<img width="245" alt="screen shot 2018-08-13 at 5 13 43 pm" src="https://user-images.githubusercontent.com/609368/44058524-557d5e60-9f1c-11e8-8016-24abe9b78ed9.png">

**Comment by escowles** [comment]
@sdellis Yes, staff suspect that users are requesting items from ReCAP because they are unaware that there are available copies.  That users want to request items from home and pick them up at one place, is interesting, but I don’t think it’s a reason not to implement this feature.  Giving users more info on the request form, which is hopefully less overwhelming than the OL show page, seems like it will help avoid needless ReCAP requests.

**Comment by sdellis** [comment]
I think the problem here is the OL show page, which should show this information up front, rather than having it hidden in the Other Versions block. They should never get to the request page if they can see a (presumably) more convenient available copy on the OL show page.
