### ISSUE TITLE
3 /24 hour Reserves Should not have a Request button

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#421]
Record with request buttons it should not have: https://catalog.princeton.edu/catalog/1782308

Record with appropriate buttons: https://catalog.princeton.edu/catalog/529189

Issue described in: https://princeton.service-now.com/snap?sys_id=7f3be905dba404d4a341de82ca96190f&view=sp&id=ticket&table=incident

**Comment by kevinreiss** [comment]
If you look at the request form for the first bib ID:

https://catalog.princeton.edu/requests/1782308?mfhd=4056129&source=pulsearch

You'll see the 3-hour reserve copies are not requestable on that form. The issue lies somewhere in the OL codebase that decides whether or not to display the request button. The permanent location for these is "res" which is an offsite annex location where the button should be displayed so I suspect the OL code is missing something and not considering the temporary location assignment in deciding whether or not to display the button.

**Comment by carolyncole** [comment]
Here is another bad one: https://catalog.princeton.edu/catalog/4803624
