### ISSUE TITLE
Enable Paging for all circulating locations

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#438]
A temporary feature for use during the campus closure. Every location whose items circulate will now be pageable.  These paging requests should deliver an email to:

1. The circulation email address for the branch library, If the item is located in a "branch" library.
2. The main Firestone Circulation Email account.
3. The patron (with instructions about how/when they will be notified and what will happen when the item is ready for pickup by them)

**Comment by carolyncole** [comment]
An example of a  item that you can see is for a checked out item: see the OPENURL . Change form=20 from form=30 and add value=GenericRequestArticleRequest

**Comment by christinach** [comment]
https://github.com/pulibrary/requests/pull/432/files

**Comment by kevinreiss** [comment]
All locations should have a pickup location of Firestone Library.

**Comment by carolyncole** [comment]
- [ ] Change Pickup Location to always be Firestone instead of Lewis `Pickup location: Lewis Library` (https://catalog.princeton.edu/requests/10133617?mfhd=9924175&source=pulsearch)
- [ ] Change the delivery option `Pageable item at Lewis Library, will be delivered to Lewis Library Service desk on first floor.` To be `Pageable item at Firestone Library, will be delivered to Firestone Library Service desk on first floor.` (https://catalog.princeton.edu/requests/10133617?mfhd=9924175&source=pulsearch)

- [ ] Change the email confirmation to say that it is going to be picked up in Firestone
- [ ] Question for Peter Bae: `Items requested before 3:00 pm (weekdays and weekends) will be available for pickup, on the same day` Is this still true?  What is the new delivery expectations?
- [ ] For items that are not currently in Lewis and are Circulating we need to make the `Request this item` button show up For example: https://catalog-staging.princeton.edu/requests/3193478?mfhd=3511881&source=pulsearch

- [ ] Make sure the email request goes to both the branch location (location of book) and the firestone circulation desk. 

- [ ] Make sure Firestone Library only gets one email

**Comment by kevinreiss** [comment]
Message for the patron confirmation email: 

"Your request to pick this item up has been received. We will process the requests as soon as possible, but given the demand and the current circumstances some delay may occur. You will receive an email the day prior telling you the item will be available for pickup in Firestone Lobby between the hours of 12-2."

**Comment by kevinreiss** [comment]
Issue superseded by later work.
