### ISSUE TITLE
In Process/On Order Pickup List

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#63]
"Recap Reading Room" should not appear in the default public pickup lists. Example ID: 9602551

**Comment by kevinreiss** [comment]
@sdellis We may already solved this one. I can't remember. Can you review it quickly?

**Comment by sdellis** [comment]
Yes, I can verify that this is solved. The assigned pickup locations are listed in the form. I can add and remove pickup locations in my local instance of bibdata (and see them reflected in the form).  I am unable to configure a holding location to have zero pickup locations. I believe this is intended, as we were going to assign defaults for all so that they would have to have at least one.
