### ISSUE TITLE
Extra row in request form for ETAS titles

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#787]
These two example items placed under the new temporary "etas" holding location are rendering the "Help Me" get it service in one row, which should be the expected fall back behavior when no other services are available but seem to display an extra table row marked "On-Site". 

Firestone Item: https://catalog.princeton.edu/requests/162632
Recap Item: https://catalog.princeton.edu/requests/162629

**Comment by carolyncole** [comment]
This is happening because the item is marked as online, but has no URLS.  We will not get the digitization form unless the location is in a library that is open (Firestone, ect).  This will also impact where the recap requests would go since the temporary location would indicate another library.  We would need to use the permanent location for etas somehow...

**Comment by carolyncole** [comment]
Another recap item since the one above is not available: http://localhost:3000/requests/7599?mfhd=8413&source=pulsearch
