### ISSUE TITLE
Re-activate Resource Sharing Features for Charged Items

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#805]
Coinciding with re-activation of the borrow direct service. These request options will be available for only items that are charged. 

- [ ] Activate Borrow Direct "Direct Request" Feature for monographs that OCLC and or ISBN numbers.
- [ ] Create a new fallback option that will allow the patron to place a direct "Loan" request in ILLiad by leveraging the ILLiad apis. (We used to just allow the user to click through to ILLiad, so this will be much easier.)

Borrow Direct and Inter Library Loan should be the only options reactivated.  Recall should still remain inactive.

Lost item: https://catalog.princeton.edu/requests/1927831?mfhd=2201400&source=pulsearch (temporarily unavailable due to the flood use https://catalog.princeton.edu/requests/1505778?mfhd=1729547&source=pulsearch for missing no borrow direct, only ILL & https://catalog.princeton.edu/requests/946984 for borrow direct)

**Comment by carolyncole** [comment]
Here is screen capture of the old code running on borrow direct:
![Screen Shot 2020-09-10 at 11 55 38 AM](https://user-images.githubusercontent.com/1599081/92770314-d0e3ea00-f367-11ea-8ff4-553247e11989.png)

**Comment by kevinreiss** [comment]
Gem used to interact with API from our Borrow Direct system: https://github.com/jrochkind/borrow_direct.

**Comment by kevinreiss** [comment]
This route was used via AJAX by the form to search BD for a direct match via standard number, https://github.com/pulibrary/requests/blob/master/config/routes.rb#L3.

**Comment by carolyncole** [comment]
Case 1 - Borrow direct lookup succeeds  The interface allows the direct request for borrow direct.  This is part of the javascript flash message.  The javascript updates the main form to include only the borrow direct. "We have found an item in borrow direct, do you want to request it" (Case 1 will never happen because the API is down).

Case 2 - Borrow Direct Look Up does not succeed.  Allow the user to put in an Iliad loan request. "Illiad Resource sharing system and the staff will be in touch"

"Request via Borrow Direct or Inter Library Loan"

First call out to Borrow Direct API - If that succeeds respond to the user that they have made the request
   May be possible to call request item to do the search and the same time
Second call out to Illiad 
  - RequestType - "Loan"? 
 - Send different data from the "Article" request type
    https://lib-illiad.princeton.edu/illiad/illiad.dll?Action=10&Form=21 ( see required parameters)
![Screen Shot 2020-09-14 at 11 51 04 AM](https://user-images.githubusercontent.com/1599081/93108275-9a1c1580-f680-11ea-861a-57513638a0ef.png)

**Comment by carolyncole** [comment]
Fields from the for:
LoanAuthor
LoanTitle
LoanPublisher
LoanPlace
LoanDate
ItemInfo3 (Volume)
ItemInfo4 (Issue)
LoanEdition
ISSN
CallNumber
ESPNumber (oclc)
AcceptNonEnglish
CitedIn
NotWantedAfter
CitedPages (really reason for request [Item's status is missing or lost in the Main Catalog, Princeton owns this title, but it is checked out, Item's status is on order in the Main Catalog] 
Notes
