### ISSUE TITLE
Status lozenge on the UI should show either Available or Unavailable not the real status

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#946]
![Screen Shot 2021-05-21 at 10 05 28 AM](https://user-images.githubusercontent.com/1599081/119150104-2060d680-ba1c-11eb-80eb-0901e2ba2f6c.png)

**Comment by kevinreiss** [comment]
Yes, let's use the value in the "status" attribute from the current availability response. Align that with column "C" in this spreadsheet: https://docs.google.com/spreadsheets/d/1-su5GdlrIaLfiePSzwDmG6YinHBf2k5bJEodpzz8waM/edit#gid=0

**Comment by carolyncole** [comment]
Make a change here: https://github.com/pulibrary/requests/blob/main/app/models/requests/requestable_decorator.rb

**Comment by carolyncole** [comment]
Here is a possible place to add additional information. https://github.com/pulibrary/requests/blob/main/app/views/requests/request/_requestable_status.html.erb#L5

**Comment by kevinreiss** [comment]
Based on current user feedback relayed from Alma Blacklight Open Houses there is a demand for staff to see the detailed statuses somehwere and the request form is the only place it can feasibly be provided due to Alma's API limitations for records that are not in the standard "Item In Place" location, the recommendations was to print out:

"Not Available - {status_lable}"

Ex: "Not Available - Lost"

**Comment by kevinreiss** [comment]
related to #896.
